# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: npm publish

# 触发工作流程的事件
on:
  push:
    branches:
      - master
    paths:
      - 'packages/**' # 只在 packages 目录下的文件发生变化时触发
concurrency: ${{ github.workflow }}-${{ github.ref }}
# 按照顺序运行作业
jobs:
  release:
    name: NPM PUBLISH
    # 指定运行器环境
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: setup node.js 20.14.0
        uses: actions/setup-node@v4
        with:
          node-version: 20.14.0
          registry-url: https://registry.npmjs.org

      - name: install pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 9.11.0

      - name: install dependencies
        run: pnpm install

      - name: build
        run: pnpm -r build

      - name: create github releases
        id: changesets
        uses: changesets/action@v1
        with:
          title: Changeset Auto PR
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: publish
        if: steps.changesets.outputs.hasChangesets == 'false'
        run: npx changeset publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
